### PR TITLE
Load errors

### PR DESCRIPTION
**Pull request by danielgroves**
Fixes an invalid file path and syntax error preventing application from loading :)

### CODE REVIEW

**Comment by danielgroves** [comment]
Only installed it last night, so it'll be whatever the latest is on OS X 10.11 unless homebrew did something funky. Will check when I get home from work.

**Comment by pixelbreaker** [comment]
That's weird, I'm OSX, El Capitan, and updated bower a couple of days ago. Stupid Bower, Maybe I should use npm instead.

**Comment by danielgroves** [comment]
I've never really gotten on with bower... always seems to bring down more than you actually need. Can't say I tend to be using that many 3rd party libraries for the sort of stuff I'm doing at the moment though!

**Comment by pixelbreaker** [comment]
I've pushed a fix, it uses the last commit for the TileLayer caching that doesn't rely on the leaflet beta 1.0API. Should work. you might need to run `bower cache clean` before running `bower install` again.

**Comment by danielgroves** [comment]
Yep, that fix is good here too :+1:

**Pull request closed without merging**
